version: 1.0
name: VPCStackApp
resources:
  - type: cloudformation
    name: VPCStack
    path: vpc_template.yaml
    region: ap-northeast-1
    deploy_method: create
    capabilities:
      - CAPABILITY_NAMED_IAM
